### ISSUE TITLE
Invalid profile for volatility

### ISSUE THREAD

**Issue by juju4** [halpomeranz/lmg#2]
In the quick test, I did, the generated profile does not work. I got

```
Volatility Foundation Volatility Framework 2.3.1
ERROR   : volatility.commands : Invalid profile host-2014-06-13_18.37.34-profile selected
```

I asked myself it was because System.map is in boot subdir but doesn't seem so.
Zip file contains two non-empty files module.dwarf and boot/System.map-3.13.0-24-generic.

Captured system is lubuntu 14.04.

**Comment by halpomeranz** [comment]
Try the new version-- and check out the automatic volatilityrc file creation.
