### ISSUE TITLE
Error when creating profile

### ISSUE THREAD

**Issue by AlanTurnage** [halpomeranz/lmg#7]
I followed your instructions for installing everything to a thumb drive, and everything seems to work fine up until the profile creation. I get the following error in /tools/linux/module.c:150:8: error: redefinition of 'struct radix_tree_node'.
It says this is originally defined in include/linux/radix-tree.h:87:8.

I am going to comment this line out and see what happens. Any advice?

**Comment by halpomeranz** [comment]
I've been seeing this problem with Volatility's module.c and various Linux distros for a few months now. The Volatility developers are working on it, but it's difficult to create a coherent fix given all the different kernel versions out there. 

Could you please supply a copy of radix-tree.h from the system where you encountered this error? You'll find it under /usr/src/linux-headers-*/include/linux/radix-tree.h

**Comment by AlanTurnage** [comment]
I'm not sure if this is normal, but there are two directories under /usr/src: linux-headers-3.16.0-30 and linux-header-3.16.0.38. I've included both radix-tree.h files; I added the .38 to the appropriate one to distinguish between the two files. Also, I commented out the function from module.c and everything appears to works fine.

[radix-tree.zip](https://github.com/halpomeranz/lmg/files/163577/radix-tree.zip)

**Comment by halpomeranz** [comment]
Having the file in multiple directories is typical. If you diff the two files, you'll see they're the same content.

Which version of Volatility are you using? It looks like the latest version of module.c addresses the problem that you're having. You can find that file at:

https://github.com/volatilityfoundation/volatility/blob/master/tools/linux/module.c

The fix may be as simple as downloading this version of module.c and replacing the version you're having problems with.
