### ISSUE TITLE
"Still no matching kernel module found." Error

### ISSUE THREAD

**Issue by jpoling-dswrx** [halpomeranz/lmg#8]
I receive the following error on a Fedora 21 system.

`# usb/lmg -d capture/`

> > Try to build LiME kernel module? [N|y] y
> > make -C /lib/modules/4.1.13-100.fc21.x86_64/build M="/home/user/capture/lime" modules
> > make[1]: Entering directory '/usr/src/kernels/4.1.13-100.fc21.x86_64'
> >   CC [M]  /home/user/capture/lime/tcp.o
> >   CC [M]  /home/user/capture/lime/disk.o
> >   CC [M]  /home/user/capture/lime/main.o
> >   LD [M]  /home/user/capture/lime/lime.o
> >   Building modules, stage 2.
> >   MODPOST 1 modules
> >   CC      /home/user/capture/lime/lime.mod.o
> >   LD [M]  /home/user/capture/lime/lime.ko
> > make[1]: Leaving directory '/usr/src/kernels/4.1.13-100.fc21.x86_64'
> > strip --strip-unneeded lime.ko
> > mv lime.ko lime-4.1.13-100.fc21.x86_64-x86_64.ko
> > Still no matching kernel module found... exiting!

Yet, when I manually compile LiME, it is successful...

`# usb/LiME/src/make`

> > make -C /lib/modules/4.1.13-100.fc21.x86_64/build M="/home/user/LiME/src" modules
> > make[1]: Entering directory '/usr/src/kernels/4.1.13-100.fc21.x86_64'
> >   CC [M]  /home/user/LiME/src/tcp.o
> >   CC [M]  /home/user/LiME/src/disk.o
> >   CC [M]  /home/user/LiME/src/main.o
> >   LD [M]  /home/user/LiME/src/lime.o
> >   Building modules, stage 2.
> >   MODPOST 1 modules
> >   CC      /home/user/LiME/src/lime.mod.o
> >   LD [M]  /home/user/LiME/src/lime.ko
> > make[1]: Leaving directory '/usr/src/kernels/4.1.13-100.fc21.x86_64'
> > strip --strip-unneeded lime.ko
> > mv lime.ko lime-4.1.13-100.fc21.x86_64-x86_64.ko

Any idears what's going on?

**Comment by jpoling-dswrx** [comment]
I just confirmed this only happens when I specify the "-d <directory>" option. When I re-run lmg with no command line options after this error, it works.

**Comment by jpoling-dswrx** [comment]
Fix is to specify the full path via "-d /full/path/to/dir/".

**Comment by halpomeranz** [comment]
I just checked in an update to fix this issue. Tested, works for me.
